#include "arduino_threads.h"
#include "variables.h"
#include "Wire.h"

/* this part should be autogenerated */
THD_ENTER(temp_reader)
#include "temp_reader.h"
THD_DONE(temp_reader)

// A singleton called temp_reader_obj is automatically created but the user can still
// instantiate another with
// temp_reader_class myObj;

THD_ENTER(pf_reader)
#include "pf_reader.h"
THD_DONE(pf_reader)

THD_ENTER(ecc_reader)
#include "ecc_reader.h"
THD_DONE(ecc_reader)

void setup() {
  Serial.begin(115200);
  while (!Serial);
  temp_reader_obj.start();
  pf_reader_obj.start();
  ecc_reader_obj.start();
}

void loop() {
  Serial.println(temperature);          // blocks until new data is available
  //Serial.println(temperature.peek());   // returns immediately the last known value

  Serial.println("PF1550 ID: " + String(pf1550_id, HEX));
  Serial.println("ECC608 ID: " + String(ecc608_id, HEX));
}
