#include "arduino_threads.h"
#include "variables.h"

/* this part should be autogenerated */
THD_ENTER(temp_reader)
#include "temp_reader.h"
THD_DONE(temp_reader)

// A singleton called temp_reader_obj is automatically created but the user can still
// instantiate another with
// temp_reader_class myObj;

void setup() {
  Serial.begin(115200);
  while (!Serial);
  temp_reader_obj.start();
}

void loop() {
  Serial.println(temperature);          // blocks until new data is available
  Serial.println(temperature.peek());   // returns immediately the last known value
}
