name: Report PR Size Deltas

on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Comment size deltas reports to PRs
        uses: arduino/report-size-deltas@main